name: Apt based Linux (AArch64)
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        label:
          - Debian GNU/Linux Buster arm64
          - Ubuntu Bionic arm64
          - Ubuntu Focal arm64
        include:
          - label: Debian GNU/Linux Buster arm64
            rake-job: debian-buster
          - label: Ubuntu Bionic arm64
            rake-job: ubuntu-bionic
          - label: Ubuntu Focal arm64
            rake-job: ubuntu-focal
            rake-options: LINTIAN=no
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -V install ruby ruby-bundler ruby-serverspec
          sudo apt -V install qemu-user-static
          sudo gem install bundler:2.2.9 --no-document
      - name: Build deb with Docker
        run: |
          cp /usr/bin/qemu-aarch64-static td-agent/apt/${{ matrix.rake-job }}/
          rake apt:build APT_TARGETS=${{ matrix.rake-job }}-arm64 ${{ matrix.rake-options }}
      - name: Upload td-agent deb
        uses: actions/upload-artifact@master
        with:
          name: packages-${{ matrix.rake-job }}-arm64
          path: td-agent/apt/repositories
      - name: Check Package Size
        run: |
          td-agent/apt/pkgsize-test.sh ${{ matrix.rake-job }} arm64
