name: Apt based Linux
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        label:
          - Debian GNU/Linux Buster amd64
          - Ubuntu Xenial amd64
          - Ubuntu Bionic amd64
          - Ubuntu Focal amd64
        include:
          - label: Debian GNU/Linux Buster amd64
            rake-job: debian-buster
            test-docker-image: debian:buster
          - label: Ubuntu Xenial amd64
            rake-job: ubuntu-xenial
            test-docker-image: ubuntu:xenial
          - label: Ubuntu Bionic amd64
            rake-job: ubuntu-bionic
            test-docker-image: ubuntu:bionic
          - label: Ubuntu Focal amd64
            rake-job: ubuntu-focal
            test-docker-image: ubuntu:focal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -V install ruby ruby-bundler ruby-serverspec
          sudo gem install bundler:2.2.9 --no-document
      - name: Build deb with Docker
        run: |
          rake apt:build APT_TARGETS=${{ matrix.rake-job }}
      - name: Upload td-agent deb
        uses: actions/upload-artifact@master
        with:
          name: packages-${{ matrix.rake-job }}
          path: td-agent/apt/repositories
      - name: Upload td-agent-apt-source deb
        uses: actions/upload-artifact@master
        with:
          name: packages-apt-source-${{ matrix.rake-job }}
          path: td-agent-apt-source/apt/repositories
      - name: Check Package Size
        run: |
          td-agent/apt/pkgsize-test.sh ${{ matrix.rake-job }} amd64
      - name: Installation Test
        run: |
          mkdir -p .bundle
          docker run \
          --rm \
          --tty \
          --volume ${PWD}:/fluentd:ro \
          ${{ matrix.test-docker-image }} \
          /fluentd/td-agent/apt/install-test.sh
      - name: Piuparts (Install/Remove/Upgrade) Test
        run: |
          mkdir -p .bundle
          docker run \
          --privileged \
          --rm \
          --tty \
          --volume ${PWD}:/fluentd:ro \
          ${{ matrix.test-docker-image }} \
          /fluentd/td-agent/apt/piuparts-test.sh
      - name: Serverspec Test
        run: |
          mkdir -p .bundle
          docker run \
          --rm \
          --tty \
          --volume ${PWD}:/fluentd:ro \
          ${{ matrix.test-docker-image }} \
          /fluentd/td-agent/apt/serverspec-test.sh
