name: Yum based Linux
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        label:
          - CentOS 7 x86_64
          - CentOS 8 x86_64
          - CentOS Stream 8 x86_64
          - Amazon Linux 2 x86_64
        include:
          - label: CentOS 7 x86_64
            rake-job: centos-7
            test-docker-image: centos:7
            centos-stream: false
          - label: CentOS 8 x86_64
            rake-job: centos-8
            test-docker-image: centos:8
            centos-stream: false
          - label: CentOS Stream 8 x86_64
            rake-job: centos-stream-8
            test-docker-image: centos:8
            centos-stream: true
          - label: Amazon Linux 2 x86_64
            rake-job: amazonlinux-2
            test-docker-image: amazonlinux:2
            centos-stream: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -V install ruby ruby-bundler ruby-serverspec
          sudo gem install bundler:2.2.9 --no-document
      - name: Build rpm with Docker
        run: |
          rake yum:build YUM_TARGETS=${{ matrix.rake-job }}
      - name: Upload td-agent rpm
        uses: actions/upload-artifact@master
        with:
          name: packages-${{ matrix.rake-job }}
          path: td-agent/yum/repositories
      - name: Check Package Size
        run: |
          td-agent/yum/pkgsize-test.sh ${{ matrix.rake-job }} x86_64
      - name: Installation Test
        run: |
          mkdir -p .bundle
          docker run \
          --rm \
          --tty \
          --volume ${PWD}:/fluentd:ro \
          --env CENTOS_STREAM=${{ matrix.centos-stream }} \
          ${{ matrix.test-docker-image }} \
          /fluentd/td-agent/yum/install-test.sh
      - name: Serverspec Test
        run: |
          mkdir -p .bundle
          docker run \
          --rm \
          --tty \
          --volume ${PWD}:/fluentd:ro \
          --env CENTOS_STREAM=${{ matrix.centos-stream }} \
          ${{ matrix.test-docker-image }} \
          /fluentd/td-agent/yum/serverspec-test.sh
